"use client";
import { useState } from "react";

const sourceLabels={web:"웹",kakao:"카카오톡",other:"기타"};
const labels = { new:"주문접수", preparing:"준비중", shipping:"배송중", delivered:"배송완료", cancelled:"취소" };
const money = (v) => `${Number(v || 0).toLocaleString("ko-KR")}원`;
const date = (v) => v ? new Date(v).toLocaleString("ko-KR", { timeZone:"Asia/Seoul" }) : "-";
const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

export default function OrdersClient({ initialOrders, itemsByOrder={} }) {
  const [orders,setOrders]=useState(initialOrders||[]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(null); const [selected,setSelected]=useState([]); const [detail,setDetail]=useState(null);
  const updateStatus=async(id,status)=>{setBusy(id);setMessage("");try{const r=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||"상태 변경 실패");setOrders(list=>list.map(o=>o.id===id?{...o,status}:o));setMessage(`주문 #${id} 상태를 ${labels[status]}로 변경했습니다.`)}catch(e){setMessage(e.message)}finally{setBusy(null)}};
  const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const printOrders=(ids)=>{const targets=orders.filter(o=>ids.includes(o.id));if(!targets.length)return;const sections=targets.map(o=>{const items=itemsByOrder[o.id]||[];return `<section class="sheet"><header><h1>신농허브 주문서</h1><div>SHINNONG HERB</div></header><div class="meta"><p><b>주문번호</b> #${esc(o.id)}</p><p><b>주문일시</b> ${esc(date(o.created_at))}</p><p><b>거래처명</b> ${esc(o.company_name||'-')}</p><p><b>배송요청</b> ${esc(o.delivery_request||'-')}</p></div><table><thead><tr><th>상품명</th><th>규격</th><th>원산지</th><th class="num">단가</th><th class="num">수량</th><th class="num">금액</th></tr></thead><tbody>${items.length?items.map(i=>`<tr><td>${esc(i.product_name)}</td><td>${esc(i.weight||'-')}</td><td>${esc(i.origin||'-')}</td><td class="num">${esc(money(i.unit_price))}</td><td class="num">${esc(i.quantity)}</td><td class="num">${esc(money(i.subtotal))}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">주문 상세 품목이 없습니다.</td></tr>`}</tbody></table><footer><span>총 수량 <b>${items.reduce((s,i)=>s+Number(i.quantity||0),0)}</b></span><strong>총 주문금액 ${esc(money(o.total_amount))}</strong></footer></section>`}).join('');const w=window.open('','_blank','width=1000,height=800');if(!w){setMessage('팝업이 차단되어 주문서를 열 수 없습니다. 브라우저의 팝업을 허용해주세요.');return;}w.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>신농허브 주문서</title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,"Noto Sans KR",sans-serif;color:#222;margin:0}.sheet{min-height:260mm;page-break-after:always}.sheet:last-child{page-break-after:auto}header{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid #315f4e;padding-bottom:12px}h1{font-size:24px;margin:0}header div{font-size:10px;letter-spacing:2px;color:#68766f}.meta{display:grid;grid-template-columns:1fr 1fr;gap:7px 28px;padding:18px 0}.meta p{margin:0;font-size:12px}.meta b{display:inline-block;width:72px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#f4f6f4}th,td{padding:10px 8px;border-bottom:1px solid #dfe5e1;text-align:left}.num{text-align:right}.empty{text-align:center;padding:28px;color:#777}footer{display:flex;justify-content:space-between;align-items:center;padding-top:18px;font-size:12px}footer strong{font-size:15px}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body>${sections}<script>window.onload=()=>{window.print()}<\/script></body></html>`);w.document.close();};
  return <>
    {message&&<div className="adminOrderMessage">{message}</div>}
    <div className="orderPrintToolbar"><span>{selected.length ? `${selected.length}건 선택` : "출력할 주문을 선택할 수 있습니다."}</span><button disabled={!selected.length} onClick={()=>printOrders(selected)}>선택 주문 일괄 출력</button></div>
    <div className="adminTableWrap"><table className="adminTable adminOrdersTable"><thead><tr><th className="orderCheckCol">선택</th><th>주문번호</th><th>주문일시</th><th>거래처</th><th>주문경로</th><th>배송요청</th><th>금액</th><th>상태</th><th>주문서</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id}><td><input type="checkbox" aria-label={`주문 ${o.id} 선택`} checked={selected.includes(o.id)} onChange={()=>toggle(o.id)}/></td><td>#{o.id}</td><td>{date(o.created_at)}</td><td>{o.company_name}</td><td>{sourceLabels[o.order_source]||"웹"}</td><td>{o.delivery_request||"-"}</td><td>{money(o.total_amount)}</td><td><select value={o.status} disabled={busy===o.id} onChange={e=>updateStatus(o.id,e.target.value)}><option value="new">주문접수</option><option value="preparing">준비중</option><option value="shipping">배송중</option><option value="delivered">배송완료</option>{o.status!=="delivered"&&<option value="cancelled">취소</option>}</select></td><td><div className="orderPrintActions"><button className="outline" onClick={()=>setDetail(o)}>상세</button><button onClick={()=>printOrders([o.id])}>출력</button></div></td></tr>):<tr><td colSpan="9" className="emptyRow">접수된 주문이 없습니다.</td></tr>}</tbody></table></div>
    <div className="adminMobileCards">{orders.length?orders.map(o=><article key={o.id}><div><b>주문 #{o.id}</b><span className={`statusPill ${o.status}`}>{labels[o.status]||o.status}</span></div><p>{o.company_name} · {date(o.created_at)}</p><p>{sourceLabels[o.order_source]||"웹"} · {o.delivery_request||"-"} · {money(o.total_amount)}</p><select value={o.status} disabled={busy===o.id} onChange={e=>updateStatus(o.id,e.target.value)}><option value="new">주문접수</option><option value="preparing">준비중</option><option value="shipping">배송중</option><option value="delivered">배송완료</option>{o.status!=="delivered"&&<option value="cancelled">취소</option>}</select><div className="orderPrintActions mobile"><button className="outline" onClick={()=>setDetail(o)}>주문 상세</button><button onClick={()=>printOrders([o.id])}>주문서 출력</button></div></article>):<div className="emptyMobile">접수된 주문이 없습니다.</div>}</div>
    {detail&&<div className="orderDetailBackdrop" onClick={()=>setDetail(null)}><section className="orderDetailModal" onClick={e=>e.stopPropagation()}><div className="orderDetailHead"><div><span>ORDER DETAIL</span><h2>주문 #{detail.id}</h2></div><button aria-label="닫기" onClick={()=>setDetail(null)}>×</button></div><div className="orderDetailMeta"><p><b>거래처</b>{detail.company_name}</p><p><b>주문일시</b>{date(detail.created_at)}</p><p><b>주문경로</b>{sourceLabels[detail.order_source]||"웹"}</p><p><b>배송요청</b>{detail.delivery_request||"-"}</p><p><b>상태</b>{labels[detail.status]||detail.status}</p></div><div className="orderDetailItems">{(itemsByOrder[detail.id]||[]).map(i=><div key={i.id}><span><b>{i.product_name}</b><small>{i.weight||"-"} · {i.origin||"-"}</small></span><span>{money(i.unit_price)} × {i.quantity}</span><strong>{money(i.subtotal)}</strong></div>)}</div><div className="orderDetailTotal"><span>총 주문금액</span><b>{money(detail.total_amount)}</b></div><button className="orderDetailPrint" onClick={()=>printOrders([detail.id])}>주문서 출력</button></section></div>}
  </>;
}
